### ISSUE TITLE
Error when generating flamegraph with hapi framework.

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/huilu#3]
```
Debug: internal, implementation, error 
Error: Unable to detect input type for 
"{"typeId":"CPU","uid":"1","title":"genet","head":{"functionName":"(root)","url":"","lineNumber":0,"callUID":43,"bailoutReason":"","id":1,"scriptId":0,"hitCount":0,"children":[{"functionName":"parserOnHeadersComplete","url":"_http_common.js","lineNumber":45,"callUID":42,"bailoutReason":"no reason","id":2,"scriptId"
...
```

```
  at getConverter (/home/hf/dev/foo-hapi/node_modules/cpuprofilify/lib/get-converter.js:27:9)
    at CpuProfilifier.convert (/home/hf/dev/foo-hapi/node_modules/cpuprofilify/index.js:70:26)
    at Object.flamegraph (/home/hf/dev/foo-hapi/node_modules/huilu/index.js:49:30)
    at ondata (/home/hf/dev/foo-hapi/node_modules/huilu/from-stream.js:33:28)
    at ConcatStream.<anonymous> (/home/hf/dev/foo-hapi/node_modules/concat-stream/index.js:36:43)
    at emitNone (events.js:91:20)
    at ConcatStream.emit (events.js:186:7)
    at finishMaybe (/home/hf/dev/foo-hapi/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:460:14)
    at endWritable (/home/hf/dev/foo-hapi/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:469:3)
    at ConcatStream.Writable.end (/home/hf/dev/foo-hapi/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:436:5)
Debug: internal, implementation, error 
    TypeError: Cannot read property 'head' of undefined
    at CpuProfileProcessor.process (/home/hf/dev/foo-hapi/node_modules/huilu/lib/cpuprofile-processor.js:95:35)
    at fromCpuProfile (/home/hf/dev/foo-hapi/node_modules/huilu/index.js:10:57)
    at Object.flamegraph (/home/hf/dev/foo-hapi/node_modules/huilu/index.js:61:10)
    at ondata (/home/hf/dev/foo-hapi/node_modules/huilu/from-stream.js:33:28)
    at ConcatStream.<anonymous> (/home/hf/dev/foo-hapi/node_modules/concat-stream/index.js:36:43)
    at emitNone (events.js:91:20)
    at ConcatStream.emit (events.js:186:7)
    at finishMaybe (/home/hf/dev/foo-hapi/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:460:14)
    at endWritable (/home/hf/dev/foo-hapi/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:469:3)
    at ConcatStream.Writable.end (/home/hf/dev/foo-hapi/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:436:5)
```

**Comment by helio-frota** [comment]
I noticed that this error happens when genet is used inside a hapi framework function:

```
server.route({
  method: 'GET',
  path: '/slow',
  handler: (request, reply) => {
    profile.start();

    const array = Array.from({length: 64001}, () => Math.floor(Math.random() * 9));
    function test () {
      array.forEach(e => { e + 1; });
    }

    for (let i = 0; i < 1000; i++) {
      test();
    }

    profile.stop().then(() => { console.log('Profiling stopped.'); });

    reply('Hello, slow!');
  }
});
```

When running the same code outside the handler function, the flamegraph generation works fine.

**Comment by helio-frota** [comment]
The same code works with express:

```
app.get('/', function (req, res) {
  profile.start();

  const array = Array.from({length: 64001}, () => Math.floor(Math.random() * 9));
  function test () {
    array.forEach(e => { e + 1; });
  }

  for (let i = 0; i < 1000; i++) {
    test();
  }

  profile.stop().then(() => { console.log('Profiling stopped.'); });

  res.send('Hello World!');
});
```

**Comment by helio-frota** [comment]
bucharest-gold/entente#133

**Comment by helio-frota** [comment]
https://github.com/hapijs/discuss/issues/456

**Comment by helio-frota** [comment]
tested with genet 0.0.7 , same error.

**Comment by helio-frota** [comment]
https://github.com/bucharest-gold/hapi-genet
